//购物车
export const INIT_NORMAL_CART_INFO = 'INIT_NORMAL_CART_INFO';//购物车信息

//购物车结算
export const NORMAL_CART_SETTLEMENT_INFO = 'NORMAL_CART_SETTLEMENT_INFO';//购物车结算信息
export const NORMAL_CART_RESET_STATE_BEFORE_LEAVE = 'NORMAL_CART_RESET_STATE_BEFORE_LEAVE';//重置状态

//优惠券选择器
export const NORMAL_CART_SETTLEMENT_COUPON_SELECTOR_INFO = 'NORMAL_CART_SETTLEMENT_COUPON_SELECTOR_INFO';
export const NORMAL_CART_SETTLEMENT_COUPON_SELECTOR_TAB_STATE = 'NORMAL_CART_SETTLEMENT_COUPON_SELECTOR_TAB_STATE';

//配送时间选择器
export const NORMAL_CART_SETTLEMENT_DELIVERY_TIME_SELECTOR_INFO = 'NORMAL_CART_SETTLEMENT_DELIVERY_TIME_SELECTOR_INFO';
export const NORMAL_CART_SETTLEMENT_DELIVERY_TIME_SELECT = 'NORMAL_CART_SETTLEMENT_DELIVERY_TIME_SELECT';

//运费信息
export const NORMAL_CART_SETTLEMENT_FREIGHT_INFO = 'NORMAL_CART_SETTLEMENT_FREIGHT_INFO';

//余额支付信息
export const NORMAL_CART_SETTLEMENT_PAY_BY_BALANCE_INFO = 'NORMAL_CART_SETTLEMENT_PAY_BY_BALANCE_INFO';
