//改变tab栏订单的搜索状态
export const CHANGE_TAB_ORDER_STATE ="CHANGE_TAB_ORDER_STATE";
//订单列表
export const ORDER_GET_ORDER_PAGE = "ORDER_GET_ORDER_PAGE";
//订单不同状态数量
export const ORDER_GET_ORDER_COUNT_BY_ORDER_STATE = "ORDER_GET_ORDER_COUNT_BY_ORDER_STATE";
//订单列表页标题下拉框显示隐藏状态
export const ORDER_LIST_CHANGE_TITLE_SHOW_STATE = "ORDER_LIST_CHANGE_TITLE_SHOW_STATE";
//改变订单状态
export const ORDER_LIST_CHANGE_ORDER_STATE = "ORDER_LIST_CHANGE_ORDER_STATE";
//订单详情
export const ORDER_DETAIL_GET_ORDER_DETAIL = "ORDER_DETAIL_GET_ORDER_DETAIL";
//是否展示所有订单项
export const ORDER_DETAIL_CHANGE_IS_SHOW_ALL_ITEM = "ORDER_DETAIL_CHANGE_IS_SHOW_ALL_ITEM";
// 我的评价-列表
export const ORDER_PRODUCT_COMMENT_PAGE = "ORDER_PRODUCT_COMMENT_PAGE";
// 我的评价-订单评论详情
export const ORDER_PRODUCT_COMMENT_DETAILS = "ORDER_PRODUCT_COMMENT_DETAILS";
// 获取订单评论列表
export const GET_ORDER_COMMENT_LIST = "GET_ORDER_COMMENT_LIST";
// 发表评价 -订单ID
export const ORDER_PRODUCT_COMMENT_ORDER_ID = "ORDER_PRODUCT_COMMENT_ORDER_ID";
// 发表评价 -是否匿名
export const ORDER_PRODUCT_COMMENT_IS_ANONYMITY = "ORDER_PRODUCT_COMMENT_IS_ANONYMITY";
// 发表评价 -服务评分
export const ORDER_PRODUCT_COMMENT_SERVICE_GRADE = "ORDER_PRODUCT_COMMENT_SERVICE_GRADE";
// 发表评价 -发货评分
export const ORDER_PRODUCT_COMMENT_DELIVERY_GRADE = "ORDER_PRODUCT_COMMENT_DELIVERY_GRADE";
// 发表评价 -物流评分
export const ORDER_PRODUCT_COMMENT_LOGISTICS_GRADE = "ORDER_PRODUCT_COMMENT_LOGISTICS_GRADE";
// 发表评价 -初始化商品评论对象
export const ORDE_RPRODUCT_COMMENT_LIST = "ORDE_RPRODUCT_COMMENT_LIST";
// 发表评价 -订单信息
export const PUBLISH_COMMENT_ORDER_INFORMATION = "PUBLISH_COMMENT_ORDER_INFORMATION";
// 发表评价 -清空对象
export const EMPTY_OBJECT = "EMPTY_OBJECT";