/**
 * Created by admin on 2018/3/28.
 */
/*收货地址列表*/
export const ADDRESS_RECEIVER_ADDRESS_LIST = 'ADDRESS_RECEIVER_ADDRESS_LIST';
/*设置搜索地址结果*/
export const ADDRESS_SET_POIS = 'ADDRESS_SET_POIS';
/*设置选中的地址结果详情*/
export const ADDRESS_SET_SEARCH_ADDRESS_DETAIL = 'ADDRESS_SET_SEARCH_ADDRESS_DETAIL';
/*清除搜索结果详情*/
export const ADDRESS_CLEAR_SEARCH_ADDRESS_DETAIL = 'ADDRESS_CLEAR_SEARCH_ADDRESS_DETAIL';
/*清除搜索结果列表*/
export const ADDRESS_CLEAR_ADDRESS_POIS = 'ADDRESS_CLEAR_ADDRESS_POIS';
/*地址详情*/
export const ADDRESS_RECEIVER_ADDRESS_DETAIL = 'ADDRESS_RECEIVER_ADDRESS_DETAIL';
/*是否选择为默认地址*/
export const ADDRESS_IS_SELECT_DEFAULT_ADDRESS = 'ADDRESS_IS_SELECT_DEFAULT_ADDRESS';
/*设置PlaceSearch对象*/
export const ADDRESS_PLACE_SEARCH_OBJECT = 'ADDRESS_PLACE_SEARCH_OBJECT';
/*是否显示搜索地址组件*/
export const ADDRESS_IS_SHOW_ADDRESS_SEARCH_COMPONENT = 'ADDRESS_IS_SHOW_ADDRESS_SEARCH_COMPONENT';
/*是否显示添加地址组件*/
export const ADDRESS_IS_SHOW_ADD_ADDRESS_COMPONENT = 'ADDRESS_IS_SHOW_ADD_ADDRESS_COMPONENT';
/*监听地址输入框变化*/
export const ADDRESS_INPUT_ADDRESS_CHANGE = 'ADDRESS_INPUT_ADDRESS_CHANGE';
/*详细位置*/
export const FIND_DETAILED_ADDRESS = 'FIND_DETAILED_ADDRESS';
/*清除详细位置*/
export const ADDRESS_CLEAN_MAP_LOCATION = 'ADDRESS_CLEAN_MAP_LOCATION';