//更改门店商品搜索参数
export const PRODUCT_CHANGE_SHOP_PRODUCT_SEARCH_PARAMS = "PRODUCT_CHANGE_SHOP_PRODUCT_SEARCH_PARAMS";
//门店商品列表
export const PRODUCT_SHOP_PRODUCT_LIST = "PRODUCT_SHOP_PRODUCT_LIST";
//更改b2c商品搜索参数
export const PRODUCT_CHANGE_B2C_PRODUCT_SEARCH_PARAMS = "PRODUCT_CHANGE_B2C_PRODUCT_SEARCH_PARAMS";
//门店b2c列表
export const PRODUCT_B2C_PRODUCT_LIST = "PRODUCT_B2C_PRODUCT_LIST";
//商品销售分类
export const PRODUCT_SELL_CATEGORYS = "PRODUCT_SELL_CATEGORYS";
//商品管理分类
export const PRODUCT_MGR_CATEGORYS = "PRODUCT_MGR_CATEGORYS";
//商品常用管理分类
export const PRODUCT_FREQUENTLY_MGR_CATEGORY = "PRODUCT_FREQUENTLY_MGR_CATEGORY";
//商品详情
export const PRODUCT_DETAIL_DATA = "PRODUCT_DETAIL_DATA";
//商品扫码详情
export const PRODUCT_SCAN_INFO = "PRODUCT_SCAN_INFO";
//是否展示说明书
export const CHANGE_IS_SHOW_INSTRUCTIONS = "CHANGE_IS_SHOW_INSTRUCTIONS";
//切换详情tab
export const SHIFT_PRODUCT_DETAIL_TAB = "SHIFT_PRODUCT_DETAIL_TAB";
//商品评价
export const PRODUCT_ALL_COMMENT = "PRODUCT_ALL_COMMENT";
//通过评论等级查找的商品评价
export const PRODUCT_GRADE_COMMENT = "PRODUCT_GRADE_COMMENT";
//更改评论分页搜索参数
export const CHANGE_COMMENT_POINT_SEARCH_PAGE = "CHANGE_COMMENT_POINT_SEARCH_PAGE";
//切换评论等级
export const CHANGE_CURRENT_GRADE = "CHANGE_CURRENT_GRADE";
// 支持商品门店ids
export const SUPPORT_SHOP_IDS = "SUPPORT_SHOP_IDS";
//切换是否清空输入框按钮
export const PRODUCT_CHANGE_IS_SHOW_DELETE_BTN_FOR_INPUT = "PRODUCT_CHANGE_IS_SHOW_DELETE_BTN_FOR_INPUT";

//以下为demo，动作类型常量，作用类似Global.java
export const PRODUCT_DEMO_PRODUCT_LIST = "PRODUCT_DEMO_PRODUCT_LIST";


// 更改门店商品搜索参数
export const NEW_PRODUCT_CHANGE_SHOP_PRODUCT_SEARCH_PARAMS = "NEW_PRODUCT_CHANGE_SHOP_PRODUCT_SEARCH_PARAMS";
// 门店商品列表
export const NEW_PRODUCT_SHOP_PRODUCT_LIST = "NEW_PRODUCT_SHOP_PRODUCT_LIST";
// 优惠券支持商品详情
export const COUPON_PRODUCT_EMPLOY_DETAILS = "COUPON_PRODUCT_EMPLOY_DETAILS";
// 优惠券距离使用金额
export const COUPON_SHORT_MONEY = "COUPON_SHORT_MONEY";
// 折扣后金额
export const COUPON_PRODUCT_MONEY = "COUPON_PRODUCT_MONEY";