//会员卡信息
export const MEMBER_CARD_INFO = 'MEMBER_CARD_INFO';
//会员登记信息
export const MEMBER_REGISTER_INFO = 'MEMBER_REGISTER_INFO';

//提交失败
export const MEMBER_SUBMIT_STATE = 'MEMBER_SUBMIT_STATE';

export const MEMBER_CARD_GET_NEW_MEMBER_REWARD_LIST = 'MEMBER_CARD_GET_NEW_MEMBER_REWARD_LIST';
