//积分兑换记录列表
export const INTEGRAL_RECORD_GET_PAGE = 'INTEGRAL_RECORD_GET_PAGE';
//积分兑换页面右上角选择类型显示隐藏
export const INTEGRAL_RECORD_RECORD_TYPE_IS_SHOW = 'INTEGRAL_RECORD_RECORD_TYPE_IS_SHOW';
//改变积分操作类型
export const INTEGRAL_RECORD_CHANGE_TRANS_TYPE = 'INTEGRAL_RECORD_CHANGE_TRANS_TYPE';
//积分推荐商品
export const MEMBER_CENTER_INTEGRAL_GET_INTEGRAL_PRODUCT = 'MEMBER_CENTER_INTEGRAL_GET_INTEGRAL_PRODUCT';
//获取我的积分
export const MEMBER_CENTER_INTEGRAL_GET_MY_INTEGRAL = 'MEMBER_CENTER_INTEGRAL_GET_MY_INTEGRAL';

//积分商品列表-获取积分商品
export const INTEGRAL_PRODUCT_GET_PRODUCT_PAGE = 'INTEGRAL_PRODUCT_GET_PRODUCT_PAGE';
//积分商品列表-获取我的总积分
export const INTEGRAL_PRODUCT_GET_MY_INTEGRAL = 'INTEGRAL_PRODUCT_GET_MY_INTEGRAL';
//积分商品列表-更新已选择商品列表
export const INTEGRAL_PRODUCT_UPDATE_SELECTED_PRODUCTS = 'INTEGRAL_PRODUCT_UPDATE_SELECTED_PRODUCTS';
//积分商品详情-获取积分商品详情
export const INTEGRAL_PRODUCT_GET_DETAIL = 'INTEGRAL_PRODUCT_GET_DETAIL';

//积分订单列表-获取积分订单
export const INTEGRAL_ORDER_LIST_PAGE_ORDER = 'INTEGRAL_ORDER_LIST_PAGE_ORDER';
//积分订单列表-获取未发货订单数量
export const INTEGRAL_ORDER_LIST_GET_NO_SENT_ORDER_QUANTITY = 'INTEGRAL_ORDER_LIST_GET_NO_SENT_ORDER_QUANTITY';
//积分订单列表-获取未收货订单数量
export const INTEGRAL_ORDER_LIST_GET_NO_RECEIVED_ORDER_QUANTITY = 'INTEGRAL_ORDER_LIST_GET_NO_RECEIVED_ORDER_QUANTITY';
//积分订单列表-选择订单状态
export const INTEGRAL_ORDER_LIST_CHANGE_SELECTED_ORDER_STATE = 'INTEGRAL_ORDER_LIST_CHANGE_SELECTED_ORDER_STATE';
//积分订单详情
export const INTEGRAL_ORDER_GET_DETAIL = 'INTEGRAL_ORDER_GET_DETAIL';


/*会员签到积分信息*/
export const INTEGRAL_MEMBER_SIGN_IN_INTEGRAL_INFO = 'INTEGRAL_MEMBER_SIGN_IN_INTEGRAL_INFO';
/*是否显示签到成功弹层*/
export const INTEGRAL_IS_SHOW_SIGN_IN_SUCCESS_VIEW = 'INTEGRAL_IS_SHOW_SIGN_IN_SUCCESS_VIEW';
/*积分推荐商品*/
export const INTEGRAL_RECOMMEND_PRODUCT = 'INTEGRAL_RECOMMEND_PRODUCT';

//积分兑换优惠劵-列表
export const COUPON_EXCHANGE_LIST = "COUPON_EXCHANGE_LIST";
//积分兑换优惠劵-获取会员积分
export const COUPON_EXCHANGE_LIST_INTEGRAL = "COUPON_EXCHANGE_LIST_INTEGRAL";


export const INTEGRAL_TURNTABLE_GET_INIT_WINPRIZE = 'INTEGRAL_TURNTABLE_GET_INIT_WINPRIZE';
export const INTEGRAL_TURNTABLE_SET_IS_SHOW_USER_WINNING_RECORD_LAYER = 'INTEGRAL_TURNTABLE_SET_IS_SHOW_USER_WINNING_RECORD_LAYER';
export const INTEGRAL_TURNTABLE_GET_RESULT = 'INTEGRAL_TURNTABLE_GET_RESULT';
export const INTEGRAL_TURNTABLE_SET_SELECT_POINT = 'INTEGRAL_TURNTABLE_SET_SELECT_POINT';

