/**
 * Created by admin on 2018/3/27.
 */
/*个人中心首页*/
export const MEMBER_INDEX_INFO = 'MEMBER_INDEX_INFO';
/*倒计时*/
export const MEMBER_COUNT_DOWN_TIME = 'MEMBER_COUNT_DOWN_TIME';
/*会员等级*/
export const MEMBER_LEVEL_LIST = 'MEMBER_LEVEL_LIST';
/*会员权益*/
export const MEMBER_INTEREST_LIST = 'MEMBER_INTEREST_LIST';
/*是否显示权益详情*/
export const MEMBER_IS_SHOW_INTEREST_DETAIL = 'MEMBER_IS_SHOW_INTEREST_DETAIL';
/*短信发送频率*/
export const MEMBER_SEND_SMS_FREQUENCY = 'MEMBER_SEND_SMS_FREQUENCY';
/*监听输入框变化*/
export const MEMBER_INPUT_CHANGE = 'MEMBER_INPUT_CHANGE';

//注册与登录
export const MEMBER_SIGN_IN_OR_SIGN_UP_TIPS = 'MEMBER_SIGN_IN_OR_SIGN_UP_TIPS';//提示语
export const MEMBER_SIGN_IN_OR_SIGN_UP_RESEND_SMS = 'MEMBER_SIGN_IN_OR_SIGN_UP_RESEND_SMS';//重发短信
export const MEMBER_SIGN_IN_OR_SIGN_UP_SMS_RESEND_LIMIT_SECOND = 'MEMBER_SIGN_IN_OR_SIGN_UP_SMS_RESEND_LIMIT_SECOND';//重发短信时间间隔
export const MEMBER_SIGN_IN_OR_SIGN_UP_SHOW_MEMBER_NAME = 'MEMBER_SIGN_IN_OR_SIGN_UP_SHOW_MEMBER_NAME';//显示会员名称输入框
export const MEMBER_SIGN_IN_OR_SIGN_UP_RESET_INPUT = 'MEMBER_SIGN_IN_OR_SIGN_UP_RESET_INPUT';//重置表单数据
export const MEMBER_SIGN_IN_OR_SIGN_UP_RESET_STATE_BEFORE_LEAVE = 'MEMBER_SIGN_IN_OR_SIGN_UP_RESET_STATE_BEFORE_LEAVE';//重置状态

// 友德医
export const YDY_PATIENT_LIST = 'YDY_PATIENT_LIST';//患者列表
export const YDY_PATIENT_DETAIL = 'YDY_PATIENT_DETAIL';//患者详情


/** 问诊记录 - 列表*/
export const INTERROGATION_RECORD_LIST = "INTERROGATION_RECORD_LIST";
/** 问诊记录 - 详情*/
export const INTERROGATION_RECORD_DETAILS = "INTERROGATION_RECORD_DETAILS";
/** 选择门店 */
export const YDY_IN_SHOP_LIST = "YDY_IN_SHOP_LIST";

/** 储值 - 我的余额 */
export const MEMBER_STORED_VALUE_BALANCE = "MEMBER_STORED_VALUE_BALANCE";
/** 储值 - 储值规则详情 */
export const STORED_VALUE_RULE_DETAILS = "STORED_VALUE_RULE_DETAILS";
/** 储值 - 最优金额 */
export const STORED_VALUE_OPTIMAL_AMOUNT = "STORED_VALUE_OPTIMAL_AMOUNT";
/** 储值 - 改变登记信息 */
export const CHANGE_REGISTER_ID_CARD_STATE = "CHANGE_REGISTER_ID_CARD_STATE";

/** 账户交易日志列表 */
export const ACCOUNT_TRANS_LOG_LIST = "ACCOUNT_TRANS_LOG_LIST";
/** 账户交易日志详情 */
export const ACCOUNT_TRANS_LOG_DETAILS = "ACCOUNT_TRANS_LOG_DETAILS";
/** 系统时间 */
export const SYSTEM_TIME = "SYSTEM_TIME";