//初始化
export const INIT_DOUBLE_ELEVEN_INFO = 'INIT_DOUBLE_ELEVEN_INFO';// 双十一初始化
export const DOUBLE_ELEVEN_COUNT_DOWN = 'DOUBLE_ELEVEN_COUNT_DOWN';//倒计时
export const INIT_DOUBLE_TWELVE_INFO = 'INIT_DOUBLE_TWELVE_INFO';// 双十二初始化
export const INIT_NEW_MEMBER_EXCLUSIVE_INFO = 'INIT_NEW_MEMBER_EXCLUSIVE_INFO';// 新会员专题

//砍价活动 分页
export const BARGAIN_ACTIVITY_PAGE = 'BARGAIN_ACTIVITY_PAGE';
//该会员参加互助砍价活动
export const MUTUAL_BARGAIN_SHARE_RECORD_PAGE_ACTION_TYPES = 'MUTUAL_BARGAIN_SHARE_RECORD_PAGE_ACTION_TYPES';
export const FULL_REDUCTION_PRODUCT = 'FULL_REDUCTION_PRODUCT';// 满立减参与商品列表
// 砍价提货地址
export const MUTUAL_BARGAIN_ADDRESS_INIT = 'MUTUAL_BARGAIN_ADDRESS_INIT';
// 砍价结算页
export const MUTUAL_BARGAIN_SETTLEMENT_DETAIL = 'MUTUAL_BARGAIN_SETTLEMENT_DETAIL';

// 砍价更改显示tab
export const BARGAIN_ACTIVITY_UPDATE_SHOW_TAB = 'BARGAIN_ACTIVITY_UPDATE_SHOW_TAB';