export const PRESCRIPTION_ADD_SET_IS_SHOW_RULE_DESCRIPTION_LAYER = "PRESCRIPTION_ADD_SET_IS_SHOW_RULE_DESCRIPTION_LAYER";
//设置是否显示规则说明弹层
export const PRESCRIPTION_ADD_SET_IS_SHOW_NEED_INVOICE_LAYER = "PRESCRIPTION_ADD_SET_IS_SHOW_NEED_INVOICE_LAYER";
//是否显示添加地址页面
export const PRESCRIPTION_ADD_SET_IS_DECOCTION = "PRESCRIPTION_ADD_SET_IS_DECOCTION";
//是否代煎
export const PRESCRIPTION_ADD_SET_IS_GRAVIDA = "PRESCRIPTION_ADD_SET_IS_GRAVIDA";
//是否孕妇
export const PRESCRIPTION_ADD_SET_IS_EXTERNAL_USE = "PRESCRIPTION_ADD_SET_IS_EXTERNAL_USE";
//是否 外用
export const PRESCRIPTION_ADD_SET_IS_NEED_INVOICE = "PRESCRIPTION_ADD_SET_IS_NEED_INVOICE";
//是否 开具 发票
export const PRESCRIPTION_ADD_SET_USER_SEX = "PRESCRIPTION_ADD_SET_USER_SEX";
//性别类型
export const PRESCRIPTION_ADD_SET_INVOICE = "PRESCRIPTION_ADD_SET_INVOICE";
//设置 发票内容
export const PRESCRIPTION_ADD_SET_FILES = "PRESCRIPTION_ADD_SET_FILES";
//设置上传文件
export const PRESCRIPTION_ADD_SET_BUY_NUM = "PRESCRIPTION_ADD_SET_BUY_NUM";
//设置购买数量
export const PRESCRIPTION_ADD_SET_USER_REMARK = "PRESCRIPTION_ADD_SET_USER_REMARK";
//设置保存参数_备注
export const PRESCRIPTION_ADD_SET_NVOICE_TITLE = "PRESCRIPTION_ADD_SET_NVOICE_TITLE";
//设置保存参数_发票抬头
export const PRESCRIPTION_ADD_SET_NVOICE_TFN = "PRESCRIPTION_ADD_SET_NVOICE_TFN";
//设置保存参数_发票编码
export const PRESCRIPTION_ADD_SET_AGE = "PRESCRIPTION_ADD_SET_AGE";
//设置保存参数_年龄
export const PRESCRIPTION_ADD_SET_DECOCTION_RULE_DESCRIPTION = "PRESCRIPTION_ADD_SET_DECOCTION_RULE_DESCRIPTION";
//设置规则明细
export const PRESCRIPTION_ADD_SET_DECOCTION_ADDRESS = "PRESCRIPTION_ADD_SET_DECOCTION_ADDRESS";
//获取收货地址
export const PRESCRIPTION_ADD_SET_IS_SHOW_SELECT_ADDRESS_LAYER = "PRESCRIPTION_ADD_SET_IS_SHOW_SELECT_ADDRESS_LAYER";
//设置新增 地址弹窗

//拍单购药列表
export const WAP_PRESCRIPTION_LIST = "WAP_PRESCRIPTION_LIST";
//拍单购药详情
export const WAP_PRESCRIPTION_DETAIL = "WAP_PRESCRIPTION_DETAIL";
//拍单购药设置搜索参数
export const WAP_PRESCRIPTION_LIST_SET_PARAMS = "WAP_PRESCRIPTION_LIST_SET_PARAMS";
//拍单购药订单数量
export const WAP_PRESCRIPTION_LIST_GET_ORDER_NUM = "WAP_PRESCRIPTION_LIST_GET_ORDER_NUM";
//拍单购药订单发票弹窗
export const WAP_PRESCRIPTION_DETAIL_SHOW_INVOICE = "WAP_PRESCRIPTION_DETAIL_SHOW_INVOICE";
//拍单购药日志详情
export const WAP_PRESCRIPTION_LOG_DETAIL = "WAP_PRESCRIPTION_LOG_DETAIL";
//拍单购药物流信息
export const WAP_PRESCRIPTION_LOGISTICS_DETAIL = "WAP_PRESCRIPTION_LOGISTICS_DETAIL";


//处方登记
// 获取处方药商品
export const PRESCRIPTION_REGISTER_GET_PRODUCT_DETAIL = "PRESCRIPTION_REGISTER_GET_PRODUCT_DETAIL";
// 获取会员默认收货地址
export const PRESCRIPTION_REGISTER_ADDRESS = "PRESCRIPTION_REGISTER_ADDRESS";
