//活动信息
export const BARGAIN_ACTIVITY_INFO = 'BARGAIN_ACTIVITY_INFO';   //基本信息
export const BARGAIN_SET_SHOW_PRIZE_RECEIVE_LAYER = 'BARGAIN_SET_SHOW_PRIZE_RECEIVE_LAYER'; //礼品领取窗
export const BARGAIN_SET_FIRST_BARGAIN_AMOUNT = 'BARGAIN_SET_FIRST_BARGAIN_AMOUNT'; //第一次助力砍价金额
export const BARGAIN_SET_SHOW_RULE_INSTRUCTION_LAYER = 'BARGAIN_SET_SHOW_RULE_INSTRUCTION_LAYER'; //规则说明窗


