//公众号图片
export const MEMBER_PROMOTE_GET_PUBLIC_NUMBER_PICTURE= 'MEMBER_PROMOTE_GET_PUBLIC_NUMBER_PICTURE';
export const MEMBER_PROMOTE_GET_PROMOTER_LIST= 'MEMBER_PROMOTE_GET_PROMOTER_LIST';
export const MEMBER_PROMOTE_CHANGE_LAYER_STATE= 'MEMBER_PROMOTE_CHANGE_LAYER_STATE';
export const MEMBER_PROMOTE_SET_SHARER_ID= 'MEMBER_PROMOTE_SET_SHARER_ID';
export const MEMBER_PROMOTE_GET_LOGIN_MEMBER_ID= 'MEMBER_PROMOTE_GET_LOGIN_MEMBER_ID';

