//优惠券列表
export const COUPON_LIST_GET_LIST = 'COUPON_LIST_GET_PAGE';
//优惠券列表Tab类型
export const COUPON_LIST_CHANGE_TYPE = 'COUPON_LIST_CHANGE_TYPE';
//用户可领优惠券列表
export const COUPON_GET_RECEIVE_COUPON_LIST = 'COUPON_GET_RECEIVE_COUPON_LIST';
//获取扫码领取优惠卷信息
export const GET_SCAN_RECEIVE_COUPON = 'GET_SCAN_RECEIVE_COUPON';
//使用优惠卷
export const USE_COUPON = 'USE_COUPON';
//使用优惠卷结果
export const USE_COUPON_RESULT = 'USE_COUPON_RESULT';
//生成会员卡二维码
export const GENERATE_MEMBER_CARD_QR_CODE = 'GENERATE_MEMBER_CARD_QR_CODE';
//领取优惠卷发生异常
export const RECEIVE_COUPON_HAPPEN_ABNORMAL = 'RECEIVE_COUPON_HAPPEN_ABNORMAL';

//年会 获取扫码领取优惠卷信息
export const YEAR_MEETING_RECEIVE_GET_SCAN_RECEIVE_COUPON = 'YEAR_MEETING_RECEIVE_GET_SCAN_RECEIVE_COUPON';

//年会 领取优惠卷发生异常
export const YEAR_MEETING_RECEIVE_COUPON_HAPPEN_ABNORMAL = 'YEAR_MEETING_RECEIVE_COUPON_HAPPEN_ABNORMAL';

// 优惠券礼包详情
export const COUPON_GIFT_PACK_DETAILS = "COUPON_GIFT_PACK_DETAILS";
// 领取优惠券礼包
export const RECEIVE_COUPON_GIFT_PACK = "RECEIVE_COUPON_GIFT_PACK";

// 优惠券列表-新
export const NEW_COUPON_LIST_GET_PAGE = "NEW_COUPON_LIST_GET_PAGE";
// 切换优惠券分类
export const CHANGE_COUPON_CATEGORY = "CHANGE_COUPON_CATEGORY";
// 优惠券分类列表
export const COUPON_CATEGORY_LIST = "COUPON_CATEGORY_LIST";




//我的优惠列表

export  const MY_COUPON_LIST_SWITCH_CURRENT_COUPON_TYPE ="MY_COUPON_LIST_SWITCH_CURRENT_COUPON_TYPE" //切换优惠券当前类型的行为

export  const MY_COUPON_LIST_PAGE_COUPON_LIST ="MY_COUPON_LIST_PAGE_COUPON_LIST" //获取优惠券分页

//我的优惠券详情

export  const MY_COUPON_DETAIL_GET_DATA ="MY_COUPON_DETAIL_GET_DATA" //优惠券详情获取数据


//领取分享优惠卷
export  const RECEIVE_SHARE_COUPON_INFO ="RECEIVE_SHARE_COUPON_INFO";//领取分享优惠卷信息
export  const RECEIVE_COUPONS_RESULT ="RECEIVE_COUPONS_RESULT";//领取优惠卷结果

//优惠卷详情
export  const COUPON_APPLY_PRODUCT_PAGE ="COUPON_APPLY_PRODUCT_PAGE";//优惠券适用商品-分页
export  const COUPON_APPLY_STORE_LIST = "COUPON_APPLY_STORE_LIST"; //优惠券适用门店列表
export  const CHANGE_TAB_BUTTON ="CHANGE_TAB_BUTTON";//改变tab按钮

// 优惠券适用门店列表
export const COUPON_APPLY_SHOP_LIST = "COUPON_APPLY_SHOP_LIST";

// 记录优惠卷数据
export const RECORD_COUPON_DATA = "RECORD_COUPON_DATA";
